name: covid19model
dependencies:
  - r-bayesplot
  - r-data.table
  - r-envstats
  - r-lubridate
  - r-gdata
  - r-ggpubr
  - r-tidyr
  - r-dplyr
  - r-rstan
  - r-optparse
  - r-abind
  - r-svglite
  - r-jsonlite
  - r-abind
  - r-zoo
  - r-gtable
  - r-ggrepel
  - r-scales
  - r-stringr
  - r-ggplot2
  - r-ggstance
  - r-gridextra
  - r-dfoptim
channels:
  - conda-forge
