# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  docker:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Docker build
    - name: Build docker image
      run: |
        docker build -f docker/Dockerfile -t covid19model:latest .

    - name: Perform a short debug simulation run
      run: |
        docker run --rm -v $(pwd):/var/model --env DEBUG=TRUE covid19model:latest $(id -u) $(id -g)

    - name: Push image to GitHub packages
      if: github.event_name == 'push'
      run: |
        IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/covid19model:latest"
        docker tag covid19model:latest $IMAGE
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker push $IMAGE

  conda:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-18.04, windows-2019]

    steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1

    - name: Create virtual environment
      run: |
        conda env create -f environment.yml

    # conda activate does not get on well with GitHub actions so
    # work around this with conda run
    - name: Run short debug simulation
      run: |
        conda run --name covid19model Rscript base.r base
      env:
        DEBUG: "TRUE"
